apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-nginx-config
  namespace: apm-system
data:
  nginx.conf: |
    worker_processes 1;

    events {
        worker_connections 1024;
    }

    http {
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
        add_header Access-Control-Allow-Headers "Content-Type, Authorization";

        env APM_SERVER;
        env APM_TOKEN;
        env EXPRESS_SERVER;

        map $APM_SERVER $apm_server { default $APM_SERVER; }
        map $APM_TOKEN $apm_token { default $APM_TOKEN; }
        map $EXPRESS_SERVER $express_server { default $EXPRESS_SERVER; }

        server {
            listen 80;

            location /express {
                proxy_pass $express_server; 
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;

                proxy_set_header Content-Type "application/json";

                client_max_body_size 10m;

                proxy_request_buffering off;
                proxy_buffering off;
            }

            location /apm {
                proxy_pass $apm_server;

                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;

                proxy_set_header Authorization "Bearer $apm_token";
                proxy_set_header Content-Type "application/x-ndjson";

                client_max_body_size 10m;

                proxy_request_buffering off;
                proxy_buffering off;
            }
        }
    }
