apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-apm
  namespace: apm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-apm
  template:
    metadata:
      labels:
        app: express-apm
    spec:
      containers:
        - name: express-apm
          image: mockholm/use-apm-express
          ports:
            - containerPort: 3000
          env:
            - name: ELASTIC_APM_SERVICE_NAME
              value: "express-apm"
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: apm-global-config
                  key: APM_SERVER
            - name: ELASTIC_APM_ENVIRONMENT
              value: "development"
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: apm-secret
                  key: apm-token
